import { Receipt } from '../../Utils/Receipt.js';
import { images } from '../../../constants';

const burgers = [
   new Receipt(1,"Ketchup Burger Sauce",
               "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
               27,  
               "10 - 30 min",
               7.2,
               ['Burgers','Snacks','Coca','Chips','Sauces'],
               images.burger_restaurant_1,0
               ),
  new Receipt(2,"Burger Barbecue",        
                "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
                31,       
                "20 - 30 min",
                4.6,
                ['Burgers','Snacks','Coca'],
                images.burger_restaurant_2,0
                ),
  new Receipt(3,"Mayonnaise Berger",
                "Real food is packed with antioxidants and nutrients that support heart health, including magnesium and healthy fats."   ,
                24,     
                "30 - 40 min",
                5.3,
                ['Burgers','Snacks','Coca'],
                images.burger_restaurant_3,0
                ),
  new Receipt(4,"Mixed Burger",
                "Developing sustainable agriculture based on real food may help improve the health of the planet by reducing energy needs and decreasing the amount of non-biodegradable waste that humans produce (11Trusted Source)."        ,
                18,          
                "30 - 50 min",
                2.9,
                ['Burgers','Snacks','Coca'],
                images.burger_restaurant_4,0
                ),
  new Receipt(5,"Steak Beaf Burger",      
                "Foods like avocados, chia seeds, flaxseeds, and blackberries are particularly high in healthy fiber, alongside beans and legumes."   ,
                89,     
                "10 - 20 min",
                1.6,
                ['Burgers','Snacks','Coca'],
                images.burger_restaurant_5,0
                ),
  new Receipt(6,"Snacks Burger",          
                "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
                61,         
                "5 - 20 min",
                8.9,
                ['Burgers','Snacks','Coca'],
                images.burger_restaurant_6,0
                )
]
const pizzas = [
   new Receipt(11,"Pizza Sauce",
               "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
               17,  
               "5 - 30 min",
               3.9,
               ['Pizza','Coca','Chips','Sauces'],
               images.hawaiian_pizza,1
               ),
  new Receipt(12,"Pizza Steak Barbecue",        
                "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
                39,       
                "10 - 30 min",
                2.5,
                ['Pizza','Snacks','Coca'],
                images.pizza,1
                ),
  new Receipt(13,"Pizza All Sauce Barbecue",
                "Real food is packed with antioxidants and nutrients that support heart health, including magnesium and healthy fats."   ,
                56,     
                "6 - 40 min",
                7.4,
                ['Pizza','Coca'],
                images.pizza_restaurant,1
                ),
  new Receipt(14,"Mixed Pizza",
                "Developing sustainable agriculture based on real food may help improve the health of the planet by reducing energy needs and decreasing the amount of non-biodegradable waste that humans produce (11Trusted Source)."        ,
                43,          
                "3 - 50 min",
                9.2,
                ['Pizza','Chips','Snacks','Coca'],
                images.pizza_horizont1,1
                ),
  new Receipt(15,"Steak Beaf Pizza",      
                "Foods like avocados, chia seeds, flaxseeds, and blackberries are particularly high in healthy fiber, alongside beans and legumes."   ,
                12,     
                "13 - 20 min",
                1.9,
                ['Pizza','Snacks','Coca'],
                images.pizza_horizont2,1
                ),
  new Receipt(16,"Hotdog Pizza",          
                "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
                102,         
                "15 - 20 min",
                9.2,
                ['Pizza','Snacks','Coca'],
                images.pizza_horizont3,1
                ),
  new Receipt(17,"Pizza Vinisiuc With Sauces",          
                "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
                37,         
                "7 - 20 min",
                4.2,
                ['Pizza','Chips','Coca'],
                images.pizza_horizont4,1
                ),
  new Receipt(18,"Brett Jordan Pizza",          
                "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
                54,         
                "7 - 20 min",
                8.2,
                ['Pizza','Chips','Coca'],
                images.pizza_horizont5,1
                ),
 new Receipt(19,"Moroccan Sauces Pizza",          
                "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
                54,         
                "7 - 20 min",
                8.2,
                ['Pizza','Chips','Coca'],
                images.pizza_horizont6,1
                ),                      
]
const hotdogs = [
   new Receipt(21,"Hot Dog Sauce",
               "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
               17,  
               "5 - 30 min",
               3.3,
               ['Pizza','Coca','Chips','Sauces'],
               images.hot_dog_restaurant,2
               ),
  new Receipt(22,"Hot Dog Steak Chicken",        
                "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
                13,       
                "10 - 30 min",
                8.5,
                ['Pizza','Snacks','Coca'],
                images.chicago_hot_dog,2
                ),                     
]
const sushis = [
   new Receipt(31,"Sushi Barbecue",
               "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
               17,  
               "5 - 30 min",
               3.3,
               ['Pizza','Coca','Chips','Sauces'],
               images.sushi,3
               ),
  new Receipt(32,"Delicious Sushi",        
                "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
                20,       
                "30 - 40 min",
                8.5,
                ['Pizza','Snacks','Coca'],
                images.sushi_1,3
                ),                     
]
const salads = [
   new Receipt(41,"Salad Steak All freuits",
               "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
               12,  
               "5 - 10 min",
               4.3,
               ['Salad','Chips','Sauces'],
               images.salad,4
               ),
  new Receipt(42,"Salad Soup",        
                "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
                15,       
                "30 - 40 min",
                8.5,
                ['Pizza','Snacks','Coca'],
                images.sarawak_laksa,4
                ),                     
]


const datas = [
new Receipt(41,"Salad Steak All freuits",
               "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
               12,  
               "5 - 10 min",
               4.3,
               ['Salad','Chips','Sauces'],
               images.salad,4
               ),   
new Receipt(1,"Ketchup Burger Sauce",
   "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
   27,  
   "10 - 30 min",
   7.2,
   ['Burgers','Snacks','Coca','Chips','Sauces'],
   images.burger_restaurant_1,0
   ),
new Receipt(61,"Drunk with Fruits",
   "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
   27,  
   "10 - 30 min",
   7.2,
   ['Burgers','Snacks','Coca','Chips','Sauces'],
   images.drunk2,6
   ),

new Receipt(22,"Hot Dog Steak Chicken",        
    "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
    13,       
    "10 - 30 min",
    8.5,
    ['Pizza','Snacks','Coca'],
    images.chicago_hot_dog,2
    ),    
new Receipt(2,"Burger Barbecue",        
    "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
    31,       
    "20 - 30 min",
    4.6,
    ['Burgers','Snacks','Coca'],
    images.burger_restaurant_2,0
    ),

new Receipt(51,"Donut Chokolade",
    "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
    45,  
    "5 - 10 min",
    7.3,
    ['Donut','Chokolad'],
    images.donut1,5
    ), 
new Receipt(71,"Snuck Mix",
    "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
    27,  
    "10 - 30 min",
    7.2,
    ['Burgers','Snacks','Coca','Chips','Sauces'],
    images.snuck1,7
    ),
 new Receipt(72,"Snuck Eating With Milk",
    "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
    27,  
    "10 - 30 min",
    7.2,
    ['Snacks','Sauces'],
    images.snuck2,7
    ),    
new Receipt(52,"Donut freuits Mix",
    "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
    12,  
    "5 - 10 min",
    4.3,
    ['Salad','Chips','Sauces'],
    images.donut2,5
    ), 
new Receipt(42,"Salad Soup",        
    "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
    15,       
    "30 - 40 min",
    8.5,
    ['Pizza','Snacks','Coca'],
    images.sarawak_laksa,4
    ),      
new Receipt(3,"Mayonnaise Berger",
    "Real food is packed with antioxidants and nutrients that support heart health, including magnesium and healthy fats."   ,
    24,     
    "30 - 40 min",
    5.3,
    ['Burgers','Snacks','Coca'],
    images.burger_restaurant_3,0
    ),

new Receipt(53,"White Chokolade and Nutela in Donuts",
    "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
    12,  
    "5 - 10 min",
    4.3,
    ['Salad','Chips','Sauces'],
    images.donut3,5
    ), 
new Receipt(54,"Galaxy Mixed with Donuts",
    "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
    12,  
    "5 - 10 min",
    4.3,
    ['Salad','Chips','Sauces'],
    images.donut4,5
    ),     
new Receipt(4,"Mixed Burger",
    "Developing sustainable agriculture based on real food may help improve the health of the planet by reducing energy needs and decreasing the amount of non-biodegradable waste that humans produce (11Trusted Source)."        ,
    18,          
    "30 - 50 min",
    2.9,
    ['Burgers','Snacks','Coca'],
    images.burger_restaurant_4,0
    ),
    new Receipt(11,"Pizza Sauce",
    "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
    17,  
    "5 - 30 min",
    3.9,
    ['Pizza','Coca','Chips','Sauces'],
    images.hawaiian_pizza,1
    ),
new Receipt(12,"Pizza Steak Barbecue",        
     "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
     39,       
     "10 - 30 min",
     2.5,
     ['Pizza','Snacks','Coca'],
     images.pizza,1
     ),
new Receipt(31,"Sushi Barbecue",
     "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
     17,  
     "5 - 30 min",
     3.3,
     ['Pizza','Coca','Chips','Sauces'],
     images.sushi,3
     ),
new Receipt(32,"Delicious Sushi",        
      "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
      20,       
      "30 - 40 min",
      8.5,
      ['Pizza','Snacks','Coca'],
      images.sushi_1,3
      ),  
new Receipt(13,"Pizza All Sauce Barbecue",
     "Real food is packed with antioxidants and nutrients that support heart health, including magnesium and healthy fats."   ,
     56,     
     "6 - 40 min",
     7.4,
     ['Pizza','Coca'],
     images.pizza_restaurant,1
     ),
new Receipt(14,"Mixed Pizza",
     "Developing sustainable agriculture based on real food may help improve the health of the planet by reducing energy needs and decreasing the amount of non-biodegradable waste that humans produce (11Trusted Source)."        ,
     43,          
     "3 - 50 min",
     9.2,
     ['Pizza','Chips','Snacks','Coca'],
     images.pizza_horizont1,1
     ),

new Receipt(17,"Pizza Vinisiuc With Sauces",          
     "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
     37,         
     "7 - 20 min",
     4.2,
     ['Pizza','Chips','Coca'],
     images.pizza_horizont4,1
     ),
new Receipt(18,"Brett Jordan Pizza",          
     "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
     54,         
     "7 - 20 min",
     8.2,
     ['Pizza','Chips','Coca'],
     images.pizza_horizont5,1
     ),
new Receipt(19,"Moroccan Sauces Pizza",          
     "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
     54,         
     "7 - 20 min",
     8.2,
     ['Pizza','Chips','Coca'],
     images.pizza_horizont6,1
     ),     
new Receipt(60,"Juice Drunk Lemons",
     "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
     12,  
     "5 - 10 min",
     4.3,
     ['Salad','Chips','Sauces'],
     images.drunk1,6
     ),        
new Receipt(5,"Steak Beaf Burger",      
    "Foods like avocados, chia seeds, flaxseeds, and blackberries are particularly high in healthy fiber, alongside beans and legumes."   ,
    89,     
    "10 - 20 min",
    1.6,
    ['Burgers','Snacks','Coca'],
    images.burger_restaurant_5,0
    ),
new Receipt(21,"Hot Dog Sauce",
    "Unprocessed animal and plant foods provide the vitamins and minerals you need for optimal health.For instance, 1 cup (220 grams) of red bell peppers, broccoli, or orange slices contains more than 100% of the RDI for vitamin C (1, 2, 3).",
    17,  
    "5 - 30 min",
    3.3,
    ['Pizza','Coca','Chips','Sauces'],
    images.hot_dog_restaurant,2
    ),    
new Receipt(6,"Snacks Burger",          
    "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
    61,         
    "5 - 20 min",
    8.9,
    ['Burgers','Snacks','Coca'],
    images.burger_restaurant_6,0
    ),
new Receipt(62,"Mixed Juice",        
    "Some research suggests that eating sugary foods can increase your risk of obesity, insulin resistance, type 2 diabetes, fatty liver disease, and heart disease (7Trusted Source, 8Trusted Source, 9Trusted Source)."     ,
    13,       
    "10 - 30 min",
    8.5,
    ['Pizza','Snacks','Coca'],
    images.drunk3,6
    ),    
new Receipt(15,"Steak Beaf Pizza",      
    "Foods like avocados, chia seeds, flaxseeds, and blackberries are particularly high in healthy fiber, alongside beans and legumes."   ,
    12,     
    "13 - 20 min",
    1.9,
    ['Pizza','Snacks','Coca'],
    images.pizza_horizont2,1
    ),
new Receipt(16,"Hotdog Pizza",          
    "Eating a diet high in fibrous plants and unprocessed animal foods may help reduce blood sugar levels in people who have or are at risk for diabetes."       ,
    102,         
    "15 - 20 min",
    9.2,
    ['Pizza','Snacks','Coca'],
    images.pizza_horizont3,1
    ),    

]
  


export{burgers ,pizzas ,hotdogs,sushis , salads , datas};